export const WRITE_USER_INFO = "WRITE_USER_INFO";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_ROOM_AVATAR_URL = "SET_ROOM_AVATAR_URL";


export const RESET_AUTH = "RESET_AUTH";
