export const WRITE_USER_INFO = "WRITE_USER_INFO";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const RESET_AUTH = "RESET_AUTH";

export const SET_ROOMS = "SET_ROOMS"

export const FILTER_CHATROOM = "FILTER_CHATROOM";
export const CLEAR_CHATROOM_FILTER = "CLEAR_CHATROOM_FILTER"

export const WRITE_CONTEXT_SEARCH_REF = "WRITE_CONTEXT_SEARCH_REF" 

